package Excepciones.introductoria;
import java.util.InputMismatchException;
import java.util.Scanner;

public class TesteadorQA {
	

	    public static void main(String[] args) {
	        Scanner scanner = new Scanner(System.in);

	        System.out.print("Ingresa un número entero: ");
	        try {
		        int numero = scanner.nextInt(); 
		        String cadena = "";
		        System.out.println(cadena.charAt(10));
		        System.out.println("Detrás del input");
	        }
	        catch (InputMismatchException adrian) {
	        	System.out.println("Entro en el catch 1:" +adrian.getCause());
	        	System.out.println("Entro en el catch 1:" +adrian.getMessage());
	        }
	        catch (StringIndexOutOfBoundsException e) {
	        	System.out.println("Entro en el catch 2:" +e.getCause());
	        	System.out.println("Entro en el catch 1:" +e.getMessage());
	        }
	        finally {
	        	System.out.println("Pase lo que pase, salgo");
	        }
	    }
	}